name: smoke test on demand
on: [workflow_dispatch]
jobs:
  regression-on-demand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: install dependencies
        run: mvn install
      - name: maven execution
        run: mvn test -Dcucumber.filter.tags="@smoke"
      - name: Generate test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            target/cucumber-html-report.html
            target/surefire-reports/
